/*
 * Copyright 2023 the original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package pl.plantoplate.requests.groupCodeGeneration;

import com.google.gson.annotations.SerializedName;

/**
 * A model class that represents the response from the "api/invite-codes/" endpoint when generating a group code.
 */
public class GroupCodeResponse {

    @SerializedName("code")
    private String groupCode;

    /**
     * Constructor for creating a new `GroupCodeResponse` object with the given group code.
     *
     * @param groupCode The group code generated by the server.
     */
    public GroupCodeResponse(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * Returns the group code.
     *
     * @return The group code generated by the server.
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * Sets the group code.
     *
     * @param groupCode The group code generated by the server.
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }
}

